name: Deploy to GitHub pages
on:
  push:
    branches: [main]
permissions:
  contents: write
env:
  BUILD_FOLDER: .output/public
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.4
      - name: Generate static Nuxt 3 files
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - run: |
          pnpm install
          pnpm generate
      - name: Init new repo in $BUILD_FOLDER and commit generated files
        run: |
          grep -rnwl "<link rel=\"prefetch\"" $BUILD_FOLDER | xargs sed -i 's$<link rel="prefetch" href="[^"]*\.\(jpg\|png\|webm\|jpeg\|ttg\|svg\|gif\)">$$g'
          cd $BUILD_FOLDER
          touch .nojekyll
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{env.BUILD_FOLDER}}
